language: node_js
os: linux
dist: xenial
node_js:
  - 10
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  - npm run build
  - echo "fobgochod.com" >> .vuepress/dist/CNAME
    # 以下为编译PDF，耗时较长，可以考虑注释掉，手工触发
  - echo "Starting to Export PDF..."
  - sudo apt-get update
  - sudo apt-get -y install xfonts-utils fonts-droid-fallback xfonts-intl-asian
  - sudo cp .vuepress/font/*.* /usr/share/fonts/truetype/
  - sudo mkfontscale && mkfontdir && fc-cache
  - npm run export
deploy:
  - provider: pages
    strategy: git
    skip_cleanup: true
    local_dir: .vuepress/dist
    token: $gh_token
    keep_history: true
    target_branch: gh-pages
    on:
      branch: master
