name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Install and Build
        run: |
          npm install
          npm run build
          echo "fobgochod.com" >> .vuepress/dist/CNAME

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Specify runner + deployment step
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vuepress/dist
